import type { Metadata } from "next";
import { Lemon } from 'next/font/google'
import './ui/globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lemon = Lemon({ weight: ["400"],subsets:['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
